import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join, relative, resolve } from 'path';
import { stringify } from 'yaml';
import { CLOUD_COPY, writeCloudWikiPage } from './cloud.js';
import { loadConfig } from './config.js';
import { RefusalError } from './engine.js';
import { globMatches } from './glob.js';
import { clock } from './clock.js';
import { withLock } from './lock.js';
import { parseFrontmatter } from './skills.js';
import { slugify } from './spec.js';

export const WIKI_DIR = '.codeloop/wiki';
const KINDS = { gotcha: 'gotchas', decision: 'decisions', concept: 'concepts' } as const;
export type Kind = keyof typeof KINDS;
const STALE_DAYS = 90;

export interface Page {
  path: string; // relative to the project
  kind: Kind;
  title: string;
  scope: string[];
  freq: number;
  severity: 'warning' | 'critical';
  cards: string[];
  updated: string;
  promoted?: boolean;
  body: string;
}

export function listPages(projectDir: string): Page[] {
  const pages: Page[] = [];
  for (const [kind, folder] of Object.entries(KINDS) as [Kind, string][]) {
    const dir = join(projectDir, WIKI_DIR, folder);
    if (!existsSync(dir)) continue;
    for (const file of readdirSync(dir).filter(f => f.endsWith('.md') && !f.endsWith(CLOUD_COPY)).sort()) {
      const { data, body } = parseFrontmatter(readFileSync(join(dir, file), 'utf-8'));
      pages.push({
        path: `${WIKI_DIR}/${folder}/${file}`,
        kind,
        title: String(data.title ?? file.replace(/\.md$/, '')),
        scope: (data.scope as string[]) ?? [],
        freq: Number(data.freq ?? 1),
        severity: data.severity === 'critical' ? 'critical' : 'warning',
        cards: (data.cards as string[]) ?? [],
        updated: String(data.updated ?? ''),
        ...(data.promoted ? { promoted: true } : {}),
        body: body.trim(),
      });
    }
  }
  return pages;
}

/** Pages that changed here and in the cloud: the local file and the cloud version written beside it, waiting for a merge. */
export function cloudCopies(projectDir: string): { path: string; cloud: string }[] {
  return [...Object.values(KINDS), 'competitors'].flatMap(folder => {
    const dir = join(projectDir, WIKI_DIR, folder);
    if (!existsSync(dir)) return [];
    return readdirSync(dir).filter(f => f.endsWith(CLOUD_COPY)).sort().map(f => ({ path: `${WIKI_DIR}/${folder}/${f.slice(0, -CLOUD_COPY.length)}.md`, cloud: `${WIKI_DIR}/${folder}/${f}` }));
  });
}

function writePage(projectDir: string, page: Page): void {
  const { path, kind: _kind, body, ...frontmatter } = page;
  mkdirSync(dirname(join(projectDir, path)), { recursive: true });
  writeFileSync(join(projectDir, path), `---\n${stringify(frontmatter)}---\n\n${body}\n`);
}

function writeIndex(projectDir: string): void {
  const pages = listPages(projectDir);
  const lines = ['# Wiki', '', 'Generated by `codeloop wiki capture`. Run `codeloop wiki inject --files <paths>` to get the pages that apply to a change.', ''];
  for (const [kind, folder] of Object.entries(KINDS)) {
    lines.push(`## ${folder[0].toUpperCase()}${folder.slice(1)}`, '');
    const mine = pages.filter(p => p.kind === kind);
    if (mine.length === 0) lines.push('None yet.');
    for (const p of mine) lines.push(`- [${p.title}](${relative(WIKI_DIR, p.path)}): freq ${p.freq}, ${p.severity}, scope ${p.scope.join(', ') || 'none'}`);
    lines.push('');
  }
  mkdirSync(join(projectDir, WIKI_DIR), { recursive: true });
  writeFileSync(join(projectDir, WIKI_DIR, 'INDEX.md'), lines.join('\n'));
}

export function thresholds(projectDir: string): { critical: number; promote: number } {
  const config = loadConfig(projectDir);
  return { critical: config.codeloop?.critical_frequency ?? 3, promote: config.codeloop?.promote_frequency ?? 10 };
}

/** A title that already exists is the same lesson met again: its frequency goes up instead of a second page. */
export function capture(
  projectDir: string,
  input: { title: string; scope: string[]; body: string; kind?: Kind; card?: string },
  now: Date = clock(),
): Page {
  const kind = input.kind ?? 'gotcha';
  if (!KINDS[kind]) throw new RefusalError(`unknown kind "${kind}" (gotcha, decision or concept)`);
  if (!slugify(input.title)) throw new RefusalError(`wiki title "${input.title}" has no letters or digits to name its file with`);
  // A second capture of the same title reads the page, raises its frequency and writes it back.
  return withLock(join(projectDir, WIKI_DIR, 'INDEX.md'), () => captureLocked(projectDir, input, kind, now));
}

function captureLocked(projectDir: string, input: { title: string; scope: string[]; body: string; card?: string }, kind: Kind, now: Date): Page {
  const today = now.toISOString().slice(0, 10);
  const existing = listPages(projectDir).find(p => p.title.toLowerCase() === input.title.toLowerCase());
  const page: Page = existing
    ? {
        ...existing,
        freq: existing.freq + 1,
        scope: [...new Set([...existing.scope, ...input.scope])],
        cards: [...new Set([...existing.cards, ...(input.card ? [input.card] : [])])],
        updated: today,
      }
    : {
        path: `${WIKI_DIR}/${KINDS[kind]}/${slugify(input.title)}.md`,
        kind,
        title: input.title,
        scope: input.scope,
        freq: 1,
        severity: 'warning',
        cards: input.card ? [input.card] : [],
        updated: today,
        body: input.body.trim(),
      };
  if (page.freq >= thresholds(projectDir).critical) page.severity = 'critical';
  writePage(projectDir, page);
  writeIndex(projectDir);
  writeCloudWikiPage(projectDir, page.path);
  return page;
}

export function inject(projectDir: string, files: string[]): Page[] {
  const paths = files.map(f => relative(projectDir, resolve(projectDir, f)));
  return listPages(projectDir).filter(p => p.scope.some(glob => paths.some(path => globMatches(glob, path))));
}

/** Applies the frequency thresholds: critical at `critical_frequency`, copied into rules.md once at `promote_frequency`. */
export function learn(projectDir: string): { critical: string[]; promoted: string[] } {
  const { critical, promote } = thresholds(projectDir);
  const result = { critical: [] as string[], promoted: [] as string[] };
  for (const page of listPages(projectDir)) {
    let changed = false;
    if (page.freq >= critical && page.severity !== 'critical') {
      page.severity = 'critical';
      result.critical.push(page.title);
      changed = true;
    }
    if (page.freq >= promote && !page.promoted) {
      const rules = join(projectDir, '.codeloop/rules.md');
      const current = existsSync(rules) ? readFileSync(rules, 'utf-8') : '# Rules\n';
      writeFileSync(rules, `${current.trimEnd()}\n\n## ${page.title}\n\nPromoted from ${page.path} at freq ${page.freq}. Scope: ${page.scope.join(', ') || 'all'}.\n\n${page.body}\n`);
      page.promoted = true;
      result.promoted.push(page.title);
      changed = true;
    }
    if (changed) writePage(projectDir, page);
  }
  if (result.critical.length || result.promoted.length) writeIndex(projectDir);
  return result;
}

export function lintWiki(projectDir: string, now: Date = clock()): { broken: string[]; stale: string[]; duplicates: string[] } {
  const pages = listPages(projectDir);
  const broken: string[] = [];
  const files = [...pages.map(p => ({ path: p.path, text: p.body })), { path: `${WIKI_DIR}/INDEX.md`, text: existsSync(join(projectDir, WIKI_DIR, 'INDEX.md')) ? readFileSync(join(projectDir, WIKI_DIR, 'INDEX.md'), 'utf-8') : '' }];
  for (const file of files) {
    for (const m of file.text.matchAll(/\[[^\]]*\]\(([^)#\s]+)(?:#[^)]*)?\)/g)) {
      if (/^[a-z]+:/i.test(m[1])) continue;
      if (!existsSync(resolve(projectDir, dirname(file.path), m[1]))) broken.push(`${file.path}: link to ${m[1]} does not resolve`);
    }
  }
  const cutoff = new Date(now.getTime() - STALE_DAYS * 86_400_000).toISOString().slice(0, 10);
  const stale = pages.filter(p => p.updated && p.updated < cutoff).map(p => `${p.path}: last updated ${p.updated}, over ${STALE_DAYS} days ago`);
  const titles = pages.map(p => p.title.toLowerCase());
  const duplicates = pages.filter((p, i) => titles.indexOf(p.title.toLowerCase()) !== i).map(p => `${p.path}: duplicate title "${p.title}"`);
  return { broken, stale, duplicates };
}

/** Critical pages whose scope matches the files and that were not acknowledged by title. */
export function blockingGotchas(projectDir: string, files: string[], acked: string[]): Page[] {
  const ack = new Set(acked.map(t => t.toLowerCase()));
  return inject(projectDir, files).filter(p => p.severity === 'critical' && !ack.has(p.title.toLowerCase()));
}
